apiVersion: v1
kind: Service
metadata:
  name: eks-sample-linux-service
  namespace: default
  labels:
    app: eks-sample
spec:
  selector:
    app: eks-sample
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
